const cache=new Map();
async function get(url){if(cache.has(url))return cache.get(url);const p=fetch(url,{signal:AbortSignal.timeout(20000)}).then(async r=>{if(!r.ok)throw Error(`MLB HTTP ${r.status}`);const d=await r.json();if(d.message)throw Error(d.message);return d;});cache.set(url,p);try{return await p;}catch(e){cache.delete(url);throw e;}}
const base='https://statsapi.mlb.com/api/v1/';
const keys=['outs','earnedRuns','hits','baseOnBalls','strikeOuts','homeRuns','hitBatsmen'];
function totals(stats){if(!stats.length||stats.some(s=>keys.some(k=>!Number.isInteger(s[k])||s[k]<0)))return null;return Object.fromEntries(keys.map(k=>[k,stats.reduce((n,s)=>n+s[k],0)]));}
function metrics(t,c){if(!t||!t.outs)return null;const ip=t.outs/3,n=(13*t.homeRuns+3*(t.baseOnBalls+t.hitBatsmen)-2*t.strikeOuts)/ip;return {...t,innings:`${Math.floor(t.outs/3)}.${t.outs%3}`,era:9*t.earnedRuns/ip,whip:(t.hits+t.baseOnBalls)/ip,kbb:t.baseOnBalls?t.strikeOuts/t.baseOnBalls:null,fip:Number.isFinite(c)?n+c:null};}
function priorLogs(d,date){const rows=(d.stats||[]).filter(s=>s.type?.displayName==='gameLog').flatMap(s=>s.splits||[]).filter(r=>r.date<date&&r.gameType==='R');const ids=new Set();for(const r of rows){if(ids.has(r.game.gamePk))throw Error('Duplicate pitching game');ids.add(r.game.gamePk);}return rows.sort((a,b)=>a.date.localeCompare(b.date)||a.game.gamePk-b.game.gamePk);}
// Only complete innings thrown entirely by the named pitcher are used. Never assign team runs to a pitcher.
function inning(feed,id,n){if(Object.keys(feed.gameData?.game||{}).some(k=>/^resum/i.test(k)&&feed.gameData.game[k]))return null;const all=feed.liveData?.plays?.allPlays||[];const own=all.find(p=>p.about?.inning===n&&p.matchup?.pitcher?.id===id);if(!own)return null;const ps=all.filter(p=>p.about?.inning===n&&p.about?.halfInning===own.about.halfInning);if(!ps.length||ps.some(p=>!p.about.isComplete||p.matchup?.pitcher?.id!==id)||ps.at(-1).count?.outs!==3)return null;let er=0,runs=0;for(const p of ps)for(const r of p.runners||[]){if(r.details?.isScoringEvent){if(r.details.responsiblePitcher?.id!==id||typeof r.details.earned!=='boolean')return null;runs++;er+=Number(r.details.earned);}}return {outs:3,earnedRuns:er,runs};}
async function review(id,date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isSafeInteger(id)||id<=0)throw Error('Invalid pitcher/date');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(new Date());if(date>today)throw Error('Future analysis date unavailable');const end=new Date(Date.parse(date+'T12:00:00Z')-86400000).toISOString().slice(0,10),season=date.slice(0,4);const logs=priorLogs(await get(`${base}people/${id}/stats?stats=gameLog&group=pitching&season=${season}`),date);let constant=null,constantReason=null;
try{const d=await get(`${base}teams/stats?stats=byDateRange&group=pitching&sportIds=1&startDate=${season}-01-01&endDate=${end}`);const splits=d.stats?.[0]?.splits||[];if(splits.length!==30||new Set(splits.map(s=>s.team.id)).size!==30)throw Error('Incomplete MLB league totals');const t=totals(splits.map(s=>s.stat));const m=metrics(t,0);if(!m)throw Error('Invalid league totals');constant=m.era-m.fip;}catch(e){constantReason=e.message;}
const starts=logs.filter(r=>r.stat.gamesStarted===1),samples=[];let failures=0;
// Sequential requests avoid bursts to MLB; shared cache reuses previous games.
for(const r of starts){try{const feed=await get(`https://statsapi.mlb.com/api/v1.1/game/${r.game.gamePk}/feed/live`);if(feed.gameData?.datetime?.officialDate!==r.date){failures++;continue;}samples.push({first:inning(feed,id,1),middle:[2,3,4,5].map(n=>inning(feed,id,n))});}catch{failures++;}}
function aggregate(rs){const good=rs.filter(Boolean),er=good.reduce((s,r)=>s+r.earnedRuns,0);return {innings:good.length,earnedRuns:er,era:good.length?er*9/good.length:null,runAllowedPct:good.length?100*good.filter(r=>r.runs>0).length/good.length:null};}
return {pitcherId:id,beforeDate:date,throughDate:end,source:'MLB Stats API; current official historical records, not archived pregame snapshots',fipConstant:constant,constantReason,season:metrics(totals(logs.map(r=>r.stat)),constant),last5:metrics(totals(logs.slice(-5).map(r=>r.stat)),constant),appearances:logs.length,starts:starts.length,firstInning:aggregate(samples.map(s=>s.first)),innings2to5:aggregate(samples.flatMap(s=>s.middle)),unavailableGames:failures,coverageNote:'Inning metrics cover only complete innings thrown entirely by this starter. Early exits and incomplete data are excluded; innings 2–5 use available complete innings. This can bias the sample. Run frequency includes earned and unearned runs.',recent:logs.slice(-5).map(r=>({date:r.date,innings:r.stat.inningsPitched,earnedRuns:r.stat.earnedRuns,strikeouts:r.stat.strikeOuts,walks:r.stat.baseOnBalls,pitches:r.stat.numberOfPitches,started:r.stat.gamesStarted===1}))};}
module.exports={review,metrics,totals,priorLogs,inning};
