import MatchupLogic from '../components/MatchupLogic';
import {useState} from 'react';
const box={padding:20,border:'1px solid #334155',borderRadius:12,marginTop:16,background:'#111827'};
const num=v=>v==null?'Unavailable':Number(v).toFixed(2);
export default function Pitching(){const [date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(new Date())),[games,setGames]=useState([]),[reports,setReports]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null);
async function load(){setBusy(true);setError('');setReports([]);try{const r=await fetch('/api/games?date='+date),d=await r.json();if(!r.ok)throw Error(d.error);setGames(d.games);}catch(e){setError(e.message);}finally{setBusy(false);}}
async function compare(g){setSelected(g);setBusy(true);setReports([]);setError('');try{const out=[];for(const side of ['away','home']){const p=g[side].probablePitcher;if(!p) {out.push({name:g[side].name,error:'Starter unavailable'});continue;}const r=await fetch(`/api/pitching-review?id=${p.id}&date=${date}`),d=await r.json();out.push({...d,name:p.fullName,team:g[side].name});}setReports(out);}catch(e){setError(e.message);}finally{setBusy(false);}}
return <main style={{background:'#070b12',color:'#e5e7eb',minHeight:'100vh',padding:24}}><div style={{maxWidth:1100,margin:'auto'}}><a href="/kalshi-results">← Kalshi results</a><p><a href="/combined">Combined predictions and win/loss record →</a></p><h1>Pregame pitching comparison</h1><p>Only games dated before the selected date. Historical starter listings may reflect later corrections. These metrics inform review; they do not generate a calibrated pick.</p><input aria-label="Analysis date" type="date" value={date} disabled={busy} onChange={e=>{setDate(e.target.value);setSelected(null);setGames([]);setReports([]);}}/><button disabled={busy} onClick={load}>Load matchups</button>{error&&<p role="alert">{error}</p>}{busy&&<p>Loading official pitching records and prior-game innings…</p>}<div>{games.map(g=><button key={g.gamePk} disabled={busy} onClick={()=>compare(g)}>{g.away.name} @ {g.home.name}</button>)}</div>{selected&&<MatchupLogic key={`${selected.gamePk}-${date}`} gamePk={selected.gamePk} date={date}/>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>{reports.map((r,i)=><section style={box} key={i}><h2>{r.name}</h2><p>{r.team}</p>{r.error?<p>{r.error}</p>:<><p>Through {r.throughDate} · {r.appearances} appearances · {r.starts} starts</p>{[['Season',r.season],['Last 5 appearances',r.last5]].map(([title,m])=><div key={title}><h3>{title}</h3><p>IP {m?.innings??'Unavailable'} · ERA {num(m?.era)} · WHIP {num(m?.whip)}</p><p>Calculated FIP {num(m?.fip)} · K/BB {num(m?.kbb)}</p><p>K {m?.strikeOuts??'—'} · BB {m?.baseOnBalls??'—'}</p></div>)}<h3>First inning</h3><p>ERA {num(r.firstInning.era)} · {r.firstInning.innings} complete innings from {r.starts} starts</p><p>Allowed a run: {num(r.firstInning.runAllowedPct)}{r.firstInning.runAllowedPct==null?'':'%'}</p><h3>Innings 2–5</h3><p>ERA {num(r.innings2to5.era)} · {r.innings2to5.innings} complete innings</p><p>{r.coverageNote}</p><p>Source failures: {r.unavailableGames}. FIP constant: {num(r.fipConstant)}. {r.constantReason}</p><details><summary>Recent workload and methodology</summary>{r.recent.map(x=><p key={x.date}>{x.date}: {x.innings} IP, {x.earnedRuns} ER, {x.strikeouts} K, {x.walks} BB, {x.pitches} pitches · {x.started?'Start':'Relief'}</p>)}<p>FIP = [13 HR + 3(BB + HBP) − 2 K] / IP + constant. Constant calculated from MLB totals through the cutoff. This is calculated FIP, not a quoted FanGraphs value. Zero walks yields unavailable K/BB rather than a finite invented ratio.</p><p>{r.source}</p></details></>}</section>)}</div></div></main>;
}
